;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env3
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c8,$c5,$c3,$c2,$c1,$02,$c0,$00,$06
@env2:
	.byte $c1,$c2,$c1,$c0,$00,$03
@env3:
	.byte $d0,$eb,$f5,$f2,$00,$03


@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $80,$32,$8d,$3a,$85,$40,$85,$3a,$8d,$3c,$85,$40,$85,$3c,$8d,$3a
	.byte $85,$32,$85,$3a,$9d
@ref1:
	.byte $32,$8d,$3a,$85,$40,$85,$3a,$8d,$3c,$85,$40,$85,$3c,$8d,$40,$85
	.byte $3a,$85,$38,$8d,$32,$8d
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref2:
	.byte $82,$1a,$8d,$22,$85,$28,$85,$22,$8d,$24,$85,$28,$85,$24,$8d,$22
	.byte $85,$1a,$85,$22,$9d
@ref3:
	.byte $1a,$8d,$22,$85,$28,$85,$22,$8d,$24,$85,$28,$85,$24,$8d,$28,$85
	.byte $22,$85,$20,$8d,$1a,$8d
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref4:
	.byte $f9,$85
@ref5:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref6:
	.byte $f9,$85
@ref7:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref8:
	.byte $f9,$85
@ref9:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
