;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_0

@sfx_ntsc_0:
	.byte $80,$f1,$81,$c9,$82,$00,$01,$80,$f2,$81,$b3,$01,$81,$96,$01,$80
	.byte $f1,$81,$86,$01,$80,$f2,$01,$80,$f3,$81,$7e,$00
